"""Parity tests for gvpy.engines.layout.ortho.trapezoid (Phase 3 port).

Each fixture under ``tools/trapezoid_harness/fixtures/*.in`` is fed
through both the C harness (``tools/trapezoid_harness/harness.exe``)
and the Python port.  The Python output must match the C harness's
saved expected output exactly.

The expected files live under ``tests/fixtures/trapezoid/*.expected``
and are regenerated by re-running the harness whenever the fixture
input changes.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from gvpy.engines.layout.ortho.trapezoid import (
    construct_trapezoids,
    format_traps,
    load_fixture,
)


FIXTURE_DIR = (
    Path(__file__).parent.parent
    / "tools" / "trapezoid_harness" / "fixtures"
)
EXPECTED_DIR = Path(__file__).parent / "fixtures" / "trapezoid"


def _fixture_names() -> list[str]:
    return sorted(p.stem for p in FIXTURE_DIR.glob("*.in"))


@pytest.mark.parametrize("name", _fixture_names())
def test_matches_c_harness(name: str):
    in_path = FIXTURE_DIR / f"{name}.in"
    expected_path = EXPECTED_DIR / f"{name}.expected"
    assert in_path.exists(), f"missing input fixture: {in_path}"
    assert expected_path.exists(), (
        f"missing expected output: {expected_path} — "
        f"regenerate via `harness.exe {in_path} > {expected_path}`"
    )

    nseg, seg, permute = load_fixture(str(in_path))
    tr = construct_trapezoids(nseg, seg, permute)

    actual = format_traps(tr)
    expected = expected_path.read_text(encoding="utf-8")

    # Normalize trailing-whitespace / CRLF drift between Windows writers.
    actual_lines = [ln.rstrip() for ln in actual.splitlines()]
    expected_lines = [ln.rstrip() for ln in expected.splitlines()]

    if actual_lines != expected_lines:
        # Render the first diverging pair for easier debugging.
        for i, (a, e) in enumerate(zip(actual_lines, expected_lines)):
            if a != e:
                pytest.fail(
                    f"fixture {name}: first divergence at line {i}\n"
                    f"  python: {a!r}\n"
                    f"  c    : {e!r}\n"
                    f"  (total: py={len(actual_lines)} c={len(expected_lines)})"
                )
        pytest.fail(
            f"fixture {name}: line count differs "
            f"(py={len(actual_lines)}, c={len(expected_lines)})"
        )


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
